all Main.java: 
	javac Main.java db/*.java models/*.java -cp lucene-4.3.1/core/lucene-core-4.3.1.jar:./lucene-4.3.1/queryparser/lucene-queryparser-4.3.1.jar:./lucene-4.3.1/analysis/common/lucene-analyzers-common-4.3.1.jar:./lucene-4.3.1/demo/lucene-demo-4.3.1.jar:mysql.jar:.

test:
	java -cp lucene-4.3.1/core/lucene-core-4.3.1.jar:./lucene-4.3.1/queryparser/lucene-queryparser-4.3.1.jar:./lucene-4.3.1/analysis/common/lucene-analyzers-common-4.3.1.jar:./lucene-4.3.1/demo/lucene-demo-4.3.1.jar:mysql.jar:. Main
